## 1. Normalization Problem

##### This problem involves normalizing a 5x5 array of random numbers using basic data preprocessing techniques. Specifically, it requires centering the data by subtracting the mean and scaling it by dividing by the standard deviation, following the normalization formula $𝑍 = (𝑋 - mean)/σ$. The goal is to generate a random 5x5 array, compute its mean and standard deviation, apply the normalization process to adjust the data, and then save the resulting normalized array to a file named X_normalized.npy.

In [47]:
import numpy as np

# Generate a random 5x5 ndarray
X = np.random.rand(5, 5)

# Calculate the mean and standard deviation
mean_X = X.mean()
std_X = X.std()

# Print the mean and standard deviation for reference
print("Mean:", mean_X)
print("Standard Deviation:", std_X)

# Normalize X using the formula Z = (X - mean)/ standard deviation
X_normalized = (X - mean_X) / std_X

# Print both the original and normalized array
print("\nOriginal Array:\n", X)
print("\nNormalized Array:\n", X_normalized)

# Save the normalized array to a file
np.save('X_normalized.npy', X_normalized)

Mean: 0.5684458838241885
Standard Deviation: 0.24213348787161743

Original Array:
 [[0.82288675 0.78730454 0.76606343 0.76119345 0.84273583]
 [0.60092527 0.63461518 0.65792548 0.89517299 0.48645884]
 [0.31000718 0.43290893 0.68738069 0.47501767 0.37872007]
 [0.1649172  0.99545554 0.13589116 0.56520546 0.59609312]
 [0.46283103 0.80067697 0.11530669 0.21550267 0.61995098]]

Normalized Array:
 [[ 1.05082889  0.90387603  0.81615124  0.79603843  1.13280467]
 [ 0.13413834  0.27327609  0.36954655  1.34936769 -0.33860268]
 [-1.0673398  -0.55976127  0.4911952  -0.38585417 -0.78355875]
 [-1.66655463  1.76352994 -1.7864308  -0.01338281  0.11418179]
 [-0.4361844   0.95910353 -1.87144373 -1.45763901  0.21271366]]


## 2. Divisible by 3 Problem

##### This problem requires creating a 10x10 NumPy array where each element is the square of the first 100 positive integers. After constructing this array, the task is to identify all the elements that are divisible by 3. Once these elements are found, they need to be saved into a file named div_by_3.npy. The goal is to generate the squared values, apply a condition to filter out those divisible by 3, and store the result in a file for later use.

In [65]:
import numpy as np

# Create an array with the first 100 positive integers
int = np.arange(1, 101)

# Square each each element to create a 10x10 array and reshape to 10x10 ndarray
A = int ** 2
A = A.reshape(10, 10) 

# Determine all elements divisible by 3
div_by_3 = A[A % 3 == 0]

# Print the array and all the elements divisible by 3
print("10x10 Array:\n", A)
print("\nElements Divisible by 3:\n", div_by_3)

# Save the result as div_by_3.npy
np.save('div_by_3.npy', div_by_3)

10x10 Array:
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Elements Divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
